SELECT * FROM customer_behavior.customers;

use customer_behavior
##Q1. Total revenue generated by male vs. female customers

SELECT 
    Gender,
    SUM(`Purchase_Amount_(USD)`) AS total_revenue
FROM customers
GROUP BY Gender;


##Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, `purchase_amount_(usd)`
FROM customers
WHERE Discount_Applied = 'Yes'
  AND `purchase_amount_(usd)` >= (
      SELECT AVG(`purchase_amount_(usd)`)
      FROM customers
  );









##Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,avg(item_purchased) as average_rating from customers
group by item_purchased
order BY average_rating DESC
limit 5 ;

##Q4. Compare the average Purchase Amount between Standard and Express Shipping.

SELECT shipping_type, avg(shipping_type) AS avg_purchase_amount FROM customers
where shipping_type in ('Standard','Express') 
group by shipping_type ;


##Q5. Do subscribers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select 
subscription_status,
avg('purchase_amount_(usd)') as average_spend,
sum('purchase_amount_(usd)') as total_revenue
from customers
group by subscription_status;







##Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select
item_purchased,
round(100.0 * SUM(case when discount_applied = 'yes' then 1 else 0 end ))/count(*) 
as discount_persentage
from customers
group by item_purchased
order by discount_persentage desc
 limit 5;


##Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select
case
when previous_purchases = 0 then 'new'
when previous_purchases between 1 and 5  then 'Returning' and 'Loyal'

end
as customers_segment,
count(*) as customer_count
from customers
group by customers_segment
order by customer_count desc;





##Q8. What are the top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customers
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank; 

##Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers,
    ROUND(
        100.0 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS subscription_rate
FROM customers
GROUP BY customer_type;



##Q10. What is the revenue contribution of each ag`e group?
SELECT
    CASE
        WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customers
GROUP BY
    CASE
        WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END
ORDER BY total_revenue DESC;
